# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    GODOT_VERSION: 3.2.2
    EXPORT_NAME: for-tomorrow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    export-linux:
        name: Linux Export
        runs-on: ubuntu-latest
        container:
            image: docker://barichello/godot-ci:3.2.2
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup
              run: |
                    mkdir -v -p ./server/build/linux ./server/build/windows ./server/build/mac ./server/build/web
                    mkdir -v -p ./client/build/linux ./client/build/windows ./client/build/mac ./client/build/web
                    mkdir -v -p ~/.local/share/godot/templates
                    mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
            - name: Linux Build
              run: godot -v --path ./server --export "Linux/X11" ./server/build/linux/$EXPORT_NAME-server.x86_64
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                    name: linux
                    path: ./build/linux/

    export-windows:
        name: Windows Export
        runs-on: ubuntu-latest
        container:
            image: docker://barichello/godot-ci:3.2.2
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup
              run: |
                    mkdir -v -p ./server/build/linux ./server/build/windows ./server/build/mac ./server/build/web
                    mkdir -v -p ./client/build/linux ./client/build/windows ./client/build/mac ./client/build/web
                    mkdir -v -p ~/.local/share/godot/templates
                    mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
            - name: Windows Build
              run: |
                    godot -v --path ./client --export "Windows Desktop" ./client/build/windows/$EXPORT_NAME-client.exe
                    godot -v --path ./server --export "Windows Desktop" ./server/build/windows/$EXPORT_NAME-server.exe
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                    name: windows
                    path: ./build/windows/

